#!/usr/bin/env python3
"""
توليد تقارير الإنذارات للمحطات النشطة
Alert Reports Generator for DESERTAS Stations

ينشئ:
- تقارير نصية (.txt) للإنذارات
- تقارير منسقة (.md) للتوثيق
- بيانات JSON للوحة التحكم
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional


class AlertReportGenerator:
    """مولد تقارير الإنذارات"""
    
    def __init__(self):
        self.alerts_dir = Path("reports/alerts")
        self.json_dir = Path("reports/json")
        self.alerts_dir.mkdir(parents=True, exist_ok=True)
        self.json_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_alert_report(
        self,
        station_id: str,
        drgis: float,
        alert_level: str,
        parameters: Dict[str, float],
        lead_time_days: float,
        recommendations: List[str]
    ) -> Dict[str, str]:
        """
        توليد تقرير إنذار لمحطة
        
        Returns:
            مسارات الملفات المُنشأة
        """
        timestamp = datetime.now()
        date_str = timestamp.strftime('%Y%m%d_%H%M%S')
        base_filename = f"ALERT_{station_id}_{date_str}"
        
        # 1. تقرير نصي (.txt)
        txt_content = self._generate_txt_alert(
            station_id, drgis, alert_level, parameters,
            lead_time_days, recommendations, timestamp
        )
        txt_path = self.alerts_dir / f"{base_filename}.txt"
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write(txt_content)
        
        # 2. تقرير منسق (.md)
        md_content = self._generate_md_alert(
            station_id, drgis, alert_level, parameters,
            lead_time_days, recommendations, timestamp
        )
        md_path = self.alerts_dir / f"{base_filename}.md"
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(md_content)
        
        # 3. بيانات JSON
        json_data = self._generate_json_alert(
            station_id, drgis, alert_level, parameters,
            lead_time_days, recommendations, timestamp
        )
        json_path = self.json_dir / f"{base_filename}.json"
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, indent=2, ensure_ascii=False)
        
        return {
            'txt': str(txt_path),
            'md': str(md_path),
            'json': str(json_path)
        }
    
    def _generate_txt_alert(self, station_id, drgis, alert_level, parameters,
                            lead_time_days, recommendations, timestamp) -> str:
        """توليد نص الإنذار"""
        lines = []
        lines.append("!" * 60)
        lines.append(f"🚨 DESERTAS TECTONIC ALERT - {timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("!" * 60)
        lines.append(f"\nStation: {station_id}")
        lines.append(f"Alert Level: {alert_level}")
        lines.append(f"DRGIS Score: {drgis}")
        lines.append(f"Estimated Lead Time: {lead_time_days} days")
        lines.append("\nParameters:")
        for param, value in parameters.items():
            lines.append(f"  {param}: {value}")
        lines.append("\nRECOMMENDATIONS:")
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"  {i}. {rec}")
        lines.append("\n" + "!" * 60)
        return "\n".join(lines)
    
    def _generate_md_alert(self, station_id, drgis, alert_level, parameters,
                           lead_time_days, recommendations, timestamp) -> str:
        """توليد Markdown للإنذار"""
        lines = []
        lines.append(f"# 🚨 TECTONIC ALERT - {timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append()
        lines.append(f"**Station:** `{station_id}`")
        lines.append(f"**Alert Level:** `{alert_level}`")
        lines.append(f"**DRGIS Score:** `{drgis}`")
        lines.append(f"**Estimated Lead Time:** `{lead_time_days} days`")
        lines.append()
        lines.append("## Parameters")
        lines.append()
        lines.append("| Parameter | Value |")
        lines.append("|-----------|-------|")
        for param, value in parameters.items():
            lines.append(f"| {param} | {value} |")
        lines.append()
        lines.append("## Recommendations")
        lines.append()
        for rec in recommendations:
            lines.append(f"- {rec}")
        lines.append()
        lines.append("---")
        lines.append(f"*Generated by DESERTAS Alert System*")
        return "\n".join(lines)
    
    def _generate_json_alert(self, station_id, drgis, alert_level, parameters,
                             lead_time_days, recommendations, timestamp) -> Dict:
        """توليد JSON للإنذار"""
        return {
            'metadata': {
                'type': 'tectonic_alert',
                'station_id': station_id,
                'timestamp': timestamp.isoformat(),
                'version': '1.0.0'
            },
            'alert': {
                'level': alert_level,
                'drgis_score': drgis,
                'lead_time_days': lead_time_days,
                'parameters': parameters,
                'recommendations': recommendations
            }
        }


def main():
    """Example usage"""
    generator = AlertReportGenerator()
    
    # مثال لتقرير إنذار
    files = generator.generate_alert_report(
        station_id="DES-MA-02",
        drgis=0.72,
        alert_level="EMERGENCY",
        parameters={
            'Rn_pulse': 4.2,
            'He_ratio': 1.84,
            'Γ_geo': 2.1
        },
        lead_time_days=58,
        recommendations=[
            "Activate emergency protocols",
            "Notify civil protection",
            "Prepare for possible evacuation"
        ]
    )
    
    print("Generated alert reports:")
    for fmt, path in files.items():
        print(f"  {fmt}: {path}")


if __name__ == "__main__":
    main()
